name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: ${{matrix.runner || matrix.os}} / ${{matrix.preset}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        preset: [ default, default-imgui, default-cairo, default-qt ]
        include:
        - os: macos-latest
          preset: default-qt
          runner: macos-15-intel

    runs-on: ${{matrix.runner || matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        submodules: true

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sed 's/#.*//' ${{github.workspace}}/.github/workflows/wx-requirements.txt | xargs sudo apt-get install
        sed 's/#.*//' ${{github.workspace}}/.github/workflows/qt-requirements.txt | xargs sudo apt-get install

    - name: Install Prerequisites macOS
      if: ${{startsWith(matrix.os, 'macos-')}}
      shell: bash
      run: |
        brew untap aws/tap || true
        brew install autoconf autoconf-archive automake libtool pkg-config
        echo "$(brew --prefix libtool)/libexec/gnubin" >> "$GITHUB_PATH"

    - name: Setup vcpkg package cache
      id: vc
      uses: LegalizeAdulthood/vcpkg-github-cache@40cd86389171f069d4524dc5c2c2588c89a93cd8 # v1.5.0
      with:
        token: ${{github.token}}
        bootstrap: "true"
        install-nuget: "true"
        debug: "false"
        trace: "false"

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
      with:
        cmake-version: '4.3'

    - name: CMake version
      run: |
        cmake --version

    - name: CMake workflow Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      run: |
        set -o pipefail
        xvfb-run -a cmake --workflow --preset ${{matrix.preset}} 2>&1 |
          tee build.log

    - name: CMake workflow desktop
      if: ${{matrix.os != 'ubuntu-latest'}}
      shell: pwsh
      run: |
        cmake --workflow --preset ${{matrix.preset}} 2>&1 |
          Tee-Object -FilePath build.log
        if ($LASTEXITCODE -ne 0) {
          exit $LASTEXITCODE
        }

    - name: Analyze vcpkg package cache
      if: always()
      uses: LegalizeAdulthood/vcpkg-github-cache/analyze@40cd86389171f069d4524dc5c2c2588c89a93cd8 # v1.5.0
      with:
        token: ${{github.token}}
        build-log: build.log
        artifact-name: vcpkg-cache-diagnostics-${{github.job}}-${{matrix.os}}-${{matrix.preset}}
        fail-on: "never"
        debug: "false"
        trace: "false"
